ordering output transfers
multiversx/mx-chain-vm-common-go pull request #208
Opened 2023-05-19 07:35 UTC by matei-p

2023-05-19 08:06 UTC, sasurobert submitted a review, later dismissed

2023-05-24 08:50 UTC, sasurobert requested changes

2023-05-24 08:50 UTC, sasurobert commented on output.go
> +	for _, account := range vmOutput.OutputAccounts {
this is not deterministic. as the iteration on accounts is done in a map. Why is this function needed ?

2023-05-24 08:59 UTC, sasurobert requested changes

2023-05-24 08:59 UTC, sasurobert commented on interface.go
> +	NextOutputTransferIndex() uint32
add IsInterfaceNil

2023-05-24 08:59 UTC, sasurobert commented on output.go
> +func (vmOutput *VMOutput) ReindexTransfers(nextIndexProvider NextOutputTransferIndexProvider) {
add checkIfNil for nextIndexProvider

2023-05-24 08:59 UTC, sasurobert commented on output.go
> +			if int(transfer.Index) > maxTransferIndex {
why do not keep everything as uint32 ?

2023-05-25 08:51 UTC, sasurobert commented on interface.go
> +type NextOutputTransferIndexProvider interface {
add comment for public interface

2023-05-25 08:51 UTC, sasurobert commented on output.go
> +	if nextIndexProvider == nil {
if check.IfNil(nextIndexProvider)

2023-05-25 08:51 UTC, sasurobert commented on output.go
> +			if nextIndexProvider.GetCrtTransferIndex() == 0 {
you should check first whether the outPutTransfers have been indexed. If yes, then it is all good.

2023-05-25 18:44 UTC, andrei-marinica approved these changes

2023-05-25 18:51 UTC, merged